# Generated by Django 6.0.7 on 2026-07-20 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the click occurred.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Visitor IP address (IPv4 or IPv6).', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Raw user agent string of the client.', null=True)),
                ('country', models.CharField(blank=True, help_text='Geolocated country for the IP.', max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text='Geolocated city for the IP.', max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, help_text='Device type classification (mobile, desktop, tablet).', max_length=50, null=True)),
                ('browser', models.CharField(blank=True, help_text='Browser family (Chrome, Firefox, Safari, etc.).', max_length=50, null=True)),
                ('url', models.ForeignKey(help_text='The short link that was clicked.', on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='links.link')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['url', 'clicked_at'], name='analytics_c_url_id_9d95ce_idx'), models.Index(fields=['country'], name='analytics_c_country_957d7e_idx'), models.Index(fields=['city'], name='analytics_c_city_f3a2b0_idx')],
            },
        ),
    ]
