# Generated by Django 6.0.7 on 2026-07-20 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='The long URL that will be shortened.', max_length=2048)),
                ('short_code', models.CharField(blank=True, db_index=True, help_text='Automatically generated Base62 short code.', max_length=16, null=True, unique=True)),
                ('custom_alias', models.CharField(blank=True, db_index=True, help_text='Human-friendly custom alias, e.g. "my-link".', max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When set, this link stops working after this time.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete / disable flag.')),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Cached total number of clicks for quick access.')),
                ('qr_code_image', models.ImageField(blank=True, help_text='Generated QR code image pointing to this short link.', null=True, upload_to='qr_codes/')),
                ('owner', models.ForeignKey(help_text='User who created this short link.', on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['short_code'], name='links_link_short_c_886f39_idx'), models.Index(fields=['custom_alias'], name='links_link_custom__753d77_idx'), models.Index(fields=['owner', 'created_at'], name='links_link_owner_i_c76160_idx')],
            },
        ),
    ]
