# Generated by Django 6.0.7 on 2026-07-14 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='custom_alias',
            field=models.CharField(blank=True, db_index=True, help_text='Human-friendly custom alias, e.g. "my-link".', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='click_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached total number of clicks for quick access.'),
        ),
        migrations.AlterField(
            model_name='link',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When set, this link stops working after this time.', null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete / disable flag.'),
        ),
        migrations.AlterField(
            model_name='link',
            name='original_url',
            field=models.URLField(help_text='The long URL that will be shortened.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='link',
            name='owner',
            field=models.ForeignKey(help_text='User who created this short link.', on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, help_text='Automatically generated Base62 short code.', max_length=16, unique=True),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['short_code'], name='links_link_short_c_886f39_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['custom_alias'], name='links_link_custom__753d77_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['owner', 'created_at'], name='links_link_owner_i_c76160_idx'),
        ),
    ]
