# Generated by Django 6.0.7 on 2026-07-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_link_custom_alias_alter_link_click_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, help_text='Automatically generated Base62 short code.', max_length=16, null=True, unique=True),
        ),
    ]
