# Generated by Django 6.0.7 on 2026-07-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_link_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='Generated QR code image pointing to this short link.', null=True, upload_to='qr_codes/'),
        ),
    ]
